### ISSUE TITLE
Silent notifications when screen is unlocked

### ISSUE THREAD

**Issue by mooreye** [aj3423/SpamBlocker#336]
### The feature

Due to SpamBlocker taking over notifications instead of my default SMS app, the feature that most SMS apps have: that if you are texting with someone and have their conversation open, there will be no notifications: doesn't work.

So if you are actively SMS-ing with someone, you will get useless loud notifications every few seconds or so. This is especially bad in public places.

This is probably impossible to detect since every SMS app handles this with its own settings, but it would be nice if you could have a setting for all notifications to be made silent if the screen is unlocked. Or, if it is possible to detect if your SMS app is currently open, it would only then silence all SMS notifications.

**Comment by aj3423** [comment]
That makes sense.

>  all notifications to be made silent if the screen is unlocked.

There would be a problem: users listening to YouTube while not looking at the phone would miss silenced messages.

Here's the proposal:
- Silence SMS when the current foreground app is the default SMS app.
- Same as in all other SMS apps, this will be the default behavior. There will be no new setting item on UI.

**Comment by aj3423** [comment]
done: https://github.com/aj3423/SpamBlocker/actions/runs/14493068316

**Comment by mooreye** [comment]
This doesn't work for me when using QUIK sms app. I still get notifications even if conversation with this person is opened. I use version 4.10

**Comment by aj3423** [comment]
Just tested with QUIK, it works fine. 
Just to confirm:
1. Is the UsageStats permission granted? Toggle "Meeting Mode" to see if it asks for this permission.
2. Is that notification shown by QUIK or by this app?

**Comment by aj3423** [comment]
I don't want to show a popup for this, many users don't even use SMS blocking.
I plan to add a switch or a button later, once I find the ideal place. For now, it's a "hidden feature".

**Comment by mooreye** [comment]
Ok, it works fine once I granted the permission. Thank you for making this feature!

**Comment by mooreye** [comment]
Unfortunately, there is another problem I now have on GrapheneOS based on Android 16.

If you receive multiple SMSes from the same number, only the first one will be loud, no matter if your screen is locked or not. Subsequent SMSes from the same sender are silent until you dismiss the notification. They stack in the notification bar, but only the first one is loud.

**Comment by aj3423** [comment]
I can't reproduce this, tried two phones.
Can you try this test build: https://github.com/aj3423/SpamBlocker/actions/runs/16317502987

1. clear all previous notifications
2. send 2 messages to it
3. long tap the `About` button, it will generate a log file, save it.  (in the Downloads folder by default)
4. check the log for text like "isSmsAppInForeground", "isScreenOff", "isDeviceLocked"

**Comment by mooreye** [comment]
Attaching the log
[SpamBlocker.log](https://github.com/user-attachments/files/21255186/SpamBlocker.log)

**Comment by aj3423** [comment]
> Received SMS
isScreenOff: true, isDeviceLocked: true
Received SMS
isScreenOff: true, isDeviceLocked: true

When these are `true`, the following code will pick `IMPORTANCE_HIGH`:

```
importance = if (!isDeviceLocked(ctx) && isSmsAppInForeground(ctx))
                    IMPORTANCE_HIGH_MUTED
                else
                    IMPORTANCE_HIGH,
```

So it's not a bug, the OS silenced the notification channel. Have you changed anything in:
`System settings` -> `Notifications` -> `Advanced settings` ?
The `Repeat notification alerts` looks suspicious. Or any notification management feature from GrapheneOS?

**Comment by Waito2** [comment]
> Unfortunately, there is another problem I now have on GrapheneOS based on Android 16.
> 
> If you receive multiple SMSes from the same number, only the first one will be loud, no matter if your screen is locked or not. Subsequent SMSes from the same sender are silent until you dismiss the notification. They stack in the notification bar, but only the first one is loud.

I think it's the same option for loud notifications that is enabled by default in LineageOS, if you receive multiple notifications in a 2 minute period only the first notification will play and the rest will be silenced.

**Comment by mooreye** [comment]
This seems to be SpamBlocker's problem. I disabled notification snoozing and cooldown, and yet even after 5 minutes the next notification is silent. When I re-enabled notifications temporarily in QKSMS, it doesn't have this problem. It plays sound every time even if I receive SMSes with only a few seconds apart.

The difference seems to be that QUIK updates its single notification, while SpamBlocker uses grouped sub-notifications in shade area.

**Comment by aj3423** [comment]
> SpamBlocker uses grouped sub-notifications in shade area.

It doesn't group valid messages, only spams will be grouped. Are they actually grouped in the shade?

And just to confirm, are these messages allowed by the same rule?

**Comment by mooreye** [comment]
> It doesn't group valid messages, only spams will be grouped. Are they actually grouped in the shade?

Sorry, what I meant is that SpamBlocker creates separate notification for each message, and they can all be shown/collapsed by tapping the arrow next to the `SpamBlocker` app name in shade area. QUIK just shows `x new messages` in a single notification that seems to be re-created every time a new message arrives. 

> And just to confirm, are these messages allowed by the same rule?

This issue concerns non-spam messages that are allowed by default, the number they come from doesn't have any rule associated with it.

**Comment by aj3423** [comment]
> QUIK just shows x new messages in a single notification that seems to be re-created every time a new message arrives.

So QUIK groups them by default while this app doesn't, can you try this:

- Create a regex Content Rule  `.*`, priority 1000, notification type `Sound, StatusBar, Shade`
- and test again

The messages will be blocked and grouped together, see if there is the sound.

**Comment by mooreye** [comment]
Now there is a sound every time, but there are still separate notifications for each message (I can see individual sender name and msg content for each message, all within the "SpamBlocker" notification category)

**Comment by aj3423** [comment]
Please try this one, now they are always grouped together. 

On my Samsung, it stops playing sound after 24 notifications due to the well-known "Android 24 notification limit". However, it consistently plays a sound when grouped together.

https://github.com/aj3423/SpamBlocker/actions/runs/16323307634

**Comment by mooreye** [comment]
> Please try this one, now they are always grouped together.
> 
> On my Samsung, it stops playing sound after 24 notifications due to the well-known "Android 24 notification limit". However, it consistently plays a sound when grouped together.
> 
> https://github.com/aj3423/SpamBlocker/actions/runs/16323307634

This works fine, I get a sound every time now. I use Pixel 8, BTW

**Comment by aj3423** [comment]
Okay, then all notifications will be grouped.
