### ISSUE TITLE
Crash with big import

### ISSUE THREAD

**Issue by tetsumaki** [aj3423/SpamBlocker#68]
Hi, SpamBlocker 1.8 crash after a big import.
I have clearing app data, and same problem.

Step to reproduce :
- Copy json import
- Go to -> Backup & Restore
- Paste
- Wait a few seconds... freez.... crash

Sorry, but i paste the list in a paste because github limits to 65536 characters.

My generated list (click on `raw text` at the top) : https://privatebin.tetsumaki.net/?7b90d3006981fc78#F2JDXAR7mqe9vc914x73bD2mUuJ84Lt9SpD2HNYBVg78

**Comment by aj3423** [comment]
It's trying to render all items and crashes with error "out of memory", I added a limitation to the list , when it exceeds 100 items, it will be adjusted to 70% of the screen height, invisible items won't be rendered.
fixed in this action build: https://github.com/aj3423/SpamBlocker/actions/runs/9375299670

**Comment by tetsumaki** [comment]
The problem is still present after trying versions 1.10 and 1.11.  
Can i do an `adb debug` to help here or another method ?  
With an import/export from a file this could solve the problem too ?

**Comment by aj3423** [comment]
yeah, please try `adb logcat` and upload the log as a file, preferably clear the history logs before capturing, and remove any sensitive data.
I can't reproduce this, tried on Android 10 and 14.

**Comment by tetsumaki** [comment]
My smartphone : Oppo Find X5 (Android 14) with 8 real Go RAM + 8 Go (storage) RAM = 16 Go RAM

```
06-08 22:32:00.940  2090 18626 E ActivityManager: ANR in spam.blocker
06-08 22:32:00.940  2090 18626 E ActivityManager: PID: 18554
06-08 22:32:00.940  2090 18626 E ActivityManager: Reason: App requested: MainThread worked timeout
06-08 22:32:00.940  2090 18626 E ActivityManager: ErrorId: b5378630-27d4-47ac-9f32-d878790e3b65
06-08 22:32:00.940  2090 18626 E ActivityManager: Frozen: false
06-08 22:32:00.940  2090 18626 E ActivityManager: Load: 0.78 / 0.7 / 0.9
06-08 22:32:00.940  2090 18626 E ActivityManager: ----- Output from /proc/pressure/memory -----
06-08 22:32:00.940  2090 18626 E ActivityManager: some avg10=0.00 avg60=0.10 avg300=0.20 total=76265524
06-08 22:32:00.940  2090 18626 E ActivityManager: full avg10=0.00 avg60=0.06 avg300=0.10 total=31031887
06-08 22:32:00.940  2090 18626 E ActivityManager: ----- End output from /proc/pressure/memory -----
06-08 22:32:00.940  2090 18626 E ActivityManager: ----- Output from /proc/pressure/cpu -----
06-08 22:32:00.940  2090 18626 E ActivityManager: some avg10=0.62 avg60=0.57 avg300=1.76 total=4249835551
06-08 22:32:00.940  2090 18626 E ActivityManager: ----- End output from /proc/pressure/cpu -----
06-08 22:32:00.940  2090 18626 E ActivityManager: ----- Output from /proc/pressure/io -----
06-08 22:32:00.940  2090 18626 E ActivityManager: some avg10=0.00 avg60=0.00 avg300=0.06 total=199606217
06-08 22:32:00.940  2090 18626 E ActivityManager: full avg10=0.00 avg60=0.00 avg300=0.02 total=117227320
06-08 22:32:00.940  2090 18626 E ActivityManager: ----- End output from /proc/pressure/io -----
[...]
06-08 22:32:01.159  2090  2725 W WindowManager: Failed to deliver inset control state change to w=Window{25e3e7 u0 spam.blocker/spam.blocker.ui.main.MainActivity EXITING}
06-08 22:32:01.159  2090  2725 W WindowManager: android.os.DeadObjectException
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.os.BinderProxy.transactNative(Native Method)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.os.BinderProxy.transact(BinderProxy.java:685)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:498)
06-08 22:32:01.159  2090  2725 W WindowManager:         at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:4263)
06-08 22:32:01.159  2090  2725 W WindowManager:         at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:348)
06-08 22:32:01.159  2090  2725 W WindowManager:         at com.android.server.wm.InsetsStateController.$r8$lambda$8yykPRG1GyNq_J17QvL9d5xANMc(InsetsStateController.java:0)
06-08 22:32:01.159  2090  2725 W WindowManager:         at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
06-08 22:32:01.159  2090  2725 W WindowManager:         at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:305)
06-08 22:32:01.159  2090  2725 W WindowManager:         at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:213)
06-08 22:32:01.159  2090  2725 W WindowManager:         at com.android.server.wm.WindowAnimator.lambda$new$1(WindowAnimator.java:107)
06-08 22:32:01.159  2090  2725 W WindowManager:         at com.android.server.wm.WindowAnimator.$r8$lambda$aHNu1uhcqxihX5NZc4McDDQPAyw(WindowAnimator.java:0)
06-08 22:32:01.159  2090  2725 W WindowManager:         at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(R8$$SyntheticClass:0)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1542)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1553)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.view.Choreographer.doCallbacks(Choreographer.java:1109)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.view.Choreographer.doFrame(Choreographer.java:984)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1527)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.os.Handler.handleCallback(Handler.java:958)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:99)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.os.Looper.loopOnce(Looper.java:257)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.os.Looper.loop(Looper.java:368)
06-08 22:32:01.159  2090  2725 W WindowManager:         at android.os.HandlerThread.run(HandlerThread.java:67)
06-08 22:32:01.159  2090  2725 W WindowManager:         at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by aj3423** [comment]
An ANR, please check the file /data/anr/trace.txt and post the related content.

**Comment by aj3423** [comment]
Also try this action build to see if it's fixed: https://github.com/aj3423/SpamBlocker/actions/runs/9432509884

**Comment by aj3423** [comment]
Feel free to reopen if it still crashes.
